### ISSUE TITLE
connect mysql dataset error

### ISSUE THREAD

**Issue by zyyll** [mtianyan/VueDjangoAntdProBookShop#18]
when i run 
python manage.py makemigrations
some error happens as error, could you please help me:

django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Sentry responded with an error: HTTP Error 403: Forbidden (url: https://sentry.io/api/<project>/store/)
Traceback (most recent call last):
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/anaconda3/envs/delete_dj/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
['OperationalError: (2003, "Can\'t connect to MySQL server on \'127.0.0.1\' (111)")', '  File "manage.py", line 15, in <module>', '  File "django/core/management/__init__.py", line 401, in execute_from_command_line', '  File "django/core/management/__init__.py", line 395, in execute', '  File "django/core/management/base.py", line 328, in run_from_argv', '  File "django/core/management/base.py", line 366, in execute', '  File "django/core/management/base.py", line 395, in check', '  File "django/core/management/base.py", line 382, in _run_checks', '  File "django/core/checks/registry.py", line 72, in run_checks', '  File "django/core/checks/model_checks.py", line 34, in check_all_models', '  File "django/db/models/base.py", line 1274, in check', '  File "django/db/models/base.py", line 1840, in _check_constraints', '  File "django/utils/functional.py", line 48, in __get__', '  File "django/db/backends/mysql/features.py", line 93, in supports_column_check_constraints', '  File "django/utils/functional.py", line 48, in __get__', '  File "django/db/backends/mysql/base.py", line 363, in mysql_is_mariadb', '  File "django/utils/functional.py", line 48, in __get__', '  File "django/db/backends/mysql/base.py", line 350, in mysql_server_info', '  File "python3.7/contextlib.py", line 112, in __enter__', '  File "django/db/backends/base/base.py", line 604, in temporary_connection', '  File "django/utils/asyncio.py", line 24, in inner', '  File "django/db/backends/base/base.py", line 260, in cursor', '  File "django/db/backends/base/base.py", line 236, in _cursor', '  File "django/utils/asyncio.py", line 24, in inner', '  File "django/db/backends/base/base.py", line 220, in ensure_connection', '  File "django/db/utils.py", line 90, in __exit__', '  File "django/db/backends/base/base.py", line 220, in ensure_connection', '  File "django/utils/asyncio.py", line 24, in inner', '  File "django/db/backends/base/base.py", line 197, in connect', '  File "django/utils/asyncio.py", line 24, in inner', '  File "django/db/backends/mysql/base.py", line 233, in get_new_connection', '  File "MySQLdb/__init__.py", line 84, in Connect', '  File "MySQLdb/connections.py", line 164, in __init__']

**Comment by nature1995** [comment]
Change your mysql password in setting.py and local_setting.py.

**Comment by mtianyan** [comment]
Correct answer
