### ISSUE TITLE
提个小bug，结算问题

### ISSUE THREAD

**Issue by xiaoliangli1128** [mtianyan/VueDjangoAntdProBookShop#36]
去结算时，如果备注为空，点击“去结算”按钮，页面无任何反应
查看网络请求，状态码是400 bad request，服务器返回 
post_script | [ "该字段不能为空。" ]

![图片](https://user-images.githubusercontent.com/66862331/96473529-578fbf00-1264-11eb-984c-5fe59208894b.png)

**Comment by mtianyan** [comment]
@xiaoliangli1128 谢谢提醒，这个是可以优化的点，欢迎PR
