### ISSUE TITLE
您好，我已经把服务启动了，请问怎样在浏览器里查看具体的网页呢?

### ISSUE THREAD

**Issue by skyejy** [mtianyan/VueDjangoAntdProBookShop#38]
浏览器里直接输入：http://127.0.0.1:8000/
并不能看到主页出现
烦请指点一下，非常感谢

**Comment by mtianyan** [comment]
path('index/', IndexView.as_view(), name="index"),

http://127.0.0.1:8000/index

**Comment by skyejy** [comment]
> path('index/', IndexView.as_view(), name="index"),
> 
> http://127.0.0.1:8000/index

好的，非常感谢您

**Comment by skyejy** [comment]
请问您方便一个可供测试用的id和password吗？
我们尝试注册，但收不到验证码；尝试修改数据库里users_userprofile表的信息，但仍然无法登陆。

**Comment by mtianyan** [comment]
Python create superuser 就可以创建用户

**Comment by skyejy** [comment]
> Python create superuser 就可以创建用户

好的，我们试试看~多谢
