### ISSUE TITLE
python3 manage.py runserver 启动报错

### ISSUE THREAD

**Issue by Tomtao626** [mtianyan/VueDjangoAntdProBookShop#39]
python版本：3.8 
mac系统/linux系统
报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 19, in <module>
    from . import _mysql
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/MySQLdb/_mysql.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.21.dylib
  Referenced from: /usr/local/lib/python3.8/site-packages/MySQLdb/_mysql.cpython-38-darwin.so
  Reason: image not found
File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 25, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
请问是配置出问题了吗，如看到，有劳解答一下疑惑

**Comment by mtianyan** [comment]
这个看起来是你自己电脑mysql问题，百度解决一下
